# Generated by Django 2.2.1 on 2019-09-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sortable_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecolor',
            options={'ordering': ['position']},
        ),
    ]
